### ISSUE TITLE
Slack Notifier README inconsistent

### ISSUE THREAD

**Issue by Calder-Ty** [codefresh-io/plugins#34]
The README on the slack-notifier plugin is inconsistent in what to use for the environmental variable for the webhook url, it switches between:
- SLACK_WEBHOOK_URL
- SLACK_HOOK_URL
- WEBHOOK_URL

**Comment by kostis-codefresh** [comment]
Fixed by commit 796305aff5fe2d72c1c7cfa497f34f414b41582d

Thank you for reporting this.
